version: '3'
services:
  redis-backup:
    build: '.'
    environment:
      - REDIS_HOST=82.196.11.196
      - BACKUP_DIR=/data/backups/rdb
      - CRON_TIME=* * * * *
      - MAX_BACKUPS=10
    volumes:
      - './backups:/data/backups'
